import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { Crown, Users } from 'lucide-react'
import { supabase } from '../lib/supabase'
import type { Competition, Participant } from '../lib/types'

export function BattleRoomPage() {
  const { competitionId } = useParams(); const [competition, setCompetition] = useState<Competition | null>(null); const [participants, setParticipants] = useState<Participant[]>([])
  useEffect(() => { if (!supabase || !competitionId) return; const load = async () => { const [{ data: room }, { data: people }] = await Promise.all([supabase.from('competitions').select('*').eq('id', competitionId).single(), supabase.from('participants').select('id,display_name,score,joined_at').eq('competition_id', competitionId).order('joined_at')]); setCompetition(room as Competition | null); setParticipants((people as Participant[]) || []) }; load(); const channel = supabase.channel(`competition:${competitionId}`).on('postgres_changes', { event: '*', schema: 'public', table: 'participants', filter: `competition_id=eq.${competitionId}` }, load).subscribe(); return () => { supabase.removeChannel(channel) } }, [competitionId])
  if (!competition) return <main className="grid min-h-[70vh] place-items-center px-6 text-center"><div><h1 className="text-2xl font-black">Preparing your battle room…</h1><p className="mt-2 text-slate-600">If this takes a while, the room may no longer be available.</p></div></main>
  return <main className="mx-auto max-w-5xl px-6 py-12"><div className="rounded-3xl bg-ink px-8 py-12 text-center text-white"><p className="text-sm font-bold tracking-widest text-violet">YOU’RE IN THE ROOM</p><h1 className="mt-3 text-4xl font-black">{competition.title}</h1><p className="mt-5 text-slate-300">Stay ready. Your host will guide the next pronunciation challenge.</p><div className="mx-auto mt-7 w-fit rounded-xl border border-white/15 bg-white/10 px-4 py-2 font-black tracking-[.25em]">{competition.code}</div></div><section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-black"><Users className="text-violet"/> Speakers in this room</h2><span className="text-sm font-semibold text-slate-500">{participants.length} joined</span></div><ol className="mt-4 divide-y divide-slate-100">{participants.map((person, index) => <li key={person.id} className="flex items-center gap-4 py-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-slate-100 text-xs font-bold">{index + 1}</span><span className="font-semibold">{person.display_name}</span>{index === 0 && person.score > 0 && <Crown className="ml-auto h-4 w-4 text-amber-500"/>}</li>)}{participants.length === 0 && <li className="py-6 text-sm text-slate-500">You’re the first speaker here.</li>}</ol></section><p className="mt-7 text-center text-sm text-slate-500">Wrong room? <Link className="font-bold text-violet" to="/join">Join another battle</Link></p></main>
}
