import { useEffect, useState } from 'react'
import { Copy, Plus, Radio, Users } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../lib/supabase'
import type { Competition } from '../lib/types'

function makeCode() { return Array.from({ length: 6 }, () => 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random() * 32)]).join('') }

export function HostDashboardPage() {
  const { session } = useAuth(); const [items, setItems] = useState<Competition[]>([]); const [title, setTitle] = useState(''); const [creating, setCreating] = useState(false); const [error, setError] = useState('')
  const load = async () => { if (!supabase || !session) return; const { data } = await supabase.from('competitions').select('*').eq('host_id', session.user.id).order('created_at', { ascending: false }); setItems((data as Competition[]) || []) }
  useEffect(() => { load() }, [session])
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!supabase || !session || !title.trim()) return; setCreating(true); setError(''); const { error } = await supabase.from('competitions').insert({ title: title.trim(), code: makeCode(), host_id: session.user.id }); setCreating(false); if (error) setError(error.message); else { setTitle(''); load() } }
  const copy = (code: string) => navigator.clipboard.writeText(code)
  return <main className="mx-auto max-w-6xl px-6 py-12"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-bold text-violet">HOST CONSOLE</p><h1 className="mt-1 text-4xl font-black tracking-tight">Your competitions</h1><p className="mt-2 text-slate-600">Create a room, share its code, and lead the battle.</p></div><div className="rounded-xl bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-700"><Radio className="mr-2 inline h-4 w-4"/>Private host access</div></div>
  <section className="mt-9 rounded-2xl bg-ink p-6 text-white"><form onSubmit={create} className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1 text-sm font-bold">New competition name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. September Speaking Finals" className="mt-2 w-full rounded-xl border border-white/15 bg-white/10 px-4 py-3 font-normal text-white placeholder:text-slate-400 outline-none focus:border-violet"/></label><button disabled={creating} className="inline-flex items-center justify-center gap-2 rounded-xl bg-violet px-5 py-3 font-bold disabled:opacity-50"><Plus size={18}/>{creating ? 'Creating…' : 'Create competition'}</button></form>{error && <p className="mt-3 text-sm text-rose-300">{error}</p>}</section>
  <section className="mt-10"><h2 className="text-lg font-black">Recent rooms</h2><div className="mt-4 grid gap-4 md:grid-cols-2">{items.map(item => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><div><span className="rounded-full bg-violet/10 px-2.5 py-1 text-xs font-bold uppercase text-violet">{item.status}</span><h3 className="mt-3 font-bold">{item.title}</h3></div><button onClick={()=>copy(item.code)} title="Copy join code" className="rounded-xl border border-slate-200 px-3 text-sm font-black tracking-[.18em] hover:border-violet">{item.code}<Copy className="ml-2 inline h-3.5 w-3.5"/></button></div><div className="mt-5 flex items-center gap-2 text-sm text-slate-500"><Users size={16}/> Participants update live in the room</div></article>)}{items.length === 0 && <p className="rounded-2xl border border-dashed border-slate-300 p-8 text-sm text-slate-500">No competitions yet. Make your first room above.</p>}</div></section></main>
}
