import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowRight, Ticket } from 'lucide-react'
import { supabase, isSupabaseConfigured } from '../lib/supabase'

export function JoinPage() {
  const [code, setCode] = useState(''), [name, setName] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false); const navigate = useNavigate()
  const join = async (e: React.FormEvent) => { e.preventDefault(); if (!supabase) return; setBusy(true); setError(''); const normalized = code.toUpperCase().replace(/[^A-Z0-9]/g, ''); const { data, error } = await supabase.from('competitions').select('id,status').eq('code', normalized).single(); if (error || !data) { setError('We could not find an active room with that code.'); setBusy(false); return } if (data.status === 'completed') { setError('This competition has already ended.'); setBusy(false); return } const { error: participantError } = await supabase.from('participants').insert({ competition_id: data.id, display_name: name.trim() }); setBusy(false); if (participantError) setError(participantError.message); else navigate(`/battle/${data.id}`) }
  return <main className="mx-auto max-w-md px-6 py-16"><div className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-xl bg-violet/10 text-violet"><Ticket/></div><h1 className="mt-6 text-3xl font-black">Enter the battle</h1><p className="mt-2 text-sm leading-6 text-slate-600">Ask your host for the six-character room code, then tell us what to call you.</p>{!isSupabaseConfigured && <p className="mt-5 rounded-lg bg-amber-50 p-3 text-sm text-amber-800">This demo needs Supabase configuration before it can accept entries.</p>}<form onSubmit={join} className="mt-7 space-y-4"><label className="block text-sm font-bold">Competition code<input value={code} maxLength={6} required onChange={e=>setCode(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 text-center font-black tracking-[.35em] uppercase outline-none focus:border-violet" placeholder="ABC123"/></label><label className="block text-sm font-bold">Your display name<input value={name} required maxLength={40} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-slate-200 px-4 py-3 outline-none focus:border-violet" placeholder="Your name"/></label>{error && <p className="text-sm text-rose-600">{error}</p>}<button disabled={busy || !isSupabaseConfigured} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet py-3 font-bold text-white disabled:opacity-50">{busy ? 'Joining…' : 'Join competition'} <ArrowRight size={17}/></button></form></div></main>
}
